CREATE USER JOGO IDENTIFIED BY oracle;

GRANT CONNECT TO JOGO;

GRANT CONNECT, RESOURCE, DBA TO JOGO;

GRANT CREATE SESSION TO JOGO;

GRANT DBA TO JOGO;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO JOGO;

GRANT UNLIMITED TABLESPACE TO JOGO;
GRANT CREATE MATERIALIZED VIEW TO JOGO;
GRANT CREATE TABLE TO JOGO;
GRANT GLOBAL QUERY REWRITE TO JOGO;
GRANT SELECT ANY TABLE TO JOGO;