CREATE TABLE Jogo (
    ID NUMBER NOT NULL,
    nome_jogo VARCHAR2(50) UNIQUE NOT NULL,
    regras VARCHAR2(500),
    valor_inicial NUMBER(10) NOT NULL,
    CONSTRAINT PK_JOGO PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_JOGO
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE Jogador (
    ID_JOGADOR NUMBER NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    nickname VARCHAR2(100) NOT NULL UNIQUE,
    idade NUMBER NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    CONSTRAINT PK_JOGADOR PRIMARY KEY (ID_JOGADOR)
);

CREATE SEQUENCE SEQ_JOGADOR
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE Carteira (
    ID NUMBER NOT NULL,
    fichas NUMBER NOT NULL,
    dinheiro NUMBER(10,2) DEFAULT 0.00,
    id_jogador NUMBER UNIQUE NOT NULL,
    CONSTRAINT PK_CARTEIRA PRIMARY KEY (ID),
    CONSTRAINT FK_CARTEIRA_JOGADOR FOREIGN KEY (id_jogador) REFERENCES Jogador (ID_JOGADOR)
);

CREATE SEQUENCE SEQ_CARTEIRA
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;


CREATE TABLE Partida (
    id_partida NUMBER NOT NULL,
    data_hora DATE NOT NULL,
    fichas_apostadas NUMBER NOT NULL,
    ganhou CHAR(1) CHECK (ganhou IN('S', 'N')) NOT NULL,
    id_jogador NUMBER NOT NULL,
    id_jogo NUMBER NOT NULL,

    CONSTRAINT PK_PARTIDA PRIMARY KEY (id_partida),
    CONSTRAINT FK_PARTIDA_JOGADORES FOREIGN KEY (id_jogador) REFERENCES Jogador (ID_JOGADOR),
    CONSTRAINT FK_PARTIDA_JOGO FOREIGN KEY (id_jogo) REFERENCES Jogo (ID)
);

CREATE SEQUENCE SEQ_PARTIDA
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE USUARIO(
    ID_USUARIO NUMBER NOT NULL,
    LOGIN varchar2(512) UNIQUE NOT NULL,
    SENHA varchar2(512) NOT NULL,
    ATIVO CHAR(1) NOT NULL,
    PRIMARY KEY(ID_USUARIO),
    CONSTRAINT CHK_ATIVO CHECK (ATIVO IN('S', 'N'))
);

CREATE SEQUENCE seq_usuario
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;