CREATE TABLE JOGO (
    ID NUMBER PRIMARY KEY ,
    NOME_JOGO VARCHAR2(50) UNIQUE NOT NULL,
    REGRAS VARCHAR2(500),
    VALOR_INICIAL NUMBER(10) NOT NULL
);

CREATE SEQUENCE SEQ_JOGO
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

