CREATE TABLE Jogo (
    ID NUMBER PRIMARY KEY ,
    nome_jogo VARCHAR2(50) UNIQUE NOT NULL,
    regras VARCHAR2(500),
    valor_inicial NUMBER(10) NOT NULL
);

CREATE SEQUENCE SEQ_JOGO
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE Jogador (

    ID NUMBER PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    nickname VARCHAR2(100) NOT NULL UNIQUE,
    idade NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_JOGADOR
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE Carteira (
    ID NUMBER PRIMARY KEY NOT NULL,
    fichas NUMBER NOT NULL,
    dinheiro NUMBER(10,2) DEFAULT 0.00,
    id_jogador NUMBER UNIQUE NOT NULL,
    CONSTRAINT FK_CARTEIRA_JOGADOR FOREIGN KEY (id_jogador) REFERENCES Jogadores (ID)
);
