CREATE TABLE Jogo (
    ID NUMBER PRIMARY KEY ,
    nome_jogo VARCHAR2(50) UNIQUE NOT NULL,
    regras VARCHAR2(500),
    valor_inicial NUMBER(10) NOT NULL
);

CREATE SEQUENCE SEQ_JOGO
    START WITH     1
    INCREMENT BY   1
    NOCACHE NOCYCLE;

CREATE TABLE Jogadores (

    ID INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nickname VARCHAR(100) NOT NULL UNIQUE,
    idade INT NOT NULL
);

